# Generated by Django 2.2.13 on 2022-05-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
